version: '3'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    container_name: api-container
    volumes:
      - .:/workspace
    environment:
      - DB_HOST=db-container
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
    tty: true
    command: sleep infinity

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: db-container
    volumes:
      - .:/workspace
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"

# networks:
#   default:
#     external:
#       name: my-network
